services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower_test
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      WATCHTOWER_POLL_INTERVAL: "600"
      WATCHTOWER_CLEANUP: "true"
    # tell watchtower to not monitor itself
    #labels:
    #  - "com.centurylinklabs.watchtower.enable=false"
    restart: always
  UbuntuWT:
    image: ubuntu:latest
    container_name: UbuntuWT
    hostname: ubuntu_wt
    ports:
      - "8088:80"
    #command: bash -c "
    #  apt-get update &&
    #  apt-get install -y openssh-server &&
    #  echo 'root:1234' | chpasswd &&
    #  sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config &&
    #  service ssh start &&
    #  tail -f /dev/null"
    restart: always
    networks:
      ubuntu_net:
        ipv4_address: 172.28.0.8

networks:
  ubuntu_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/27