---
- name: Copy Ansible control node public key to target host
  vars:
    ansible_user: root
    ansible_ssh_pass: "1234"
    ansible_connection: ssh
  ansible.builtin.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/ansible.pub') }}"
