---
docker_compose_state: "present"
docker_compose_project_name: "default_project"
docker_compose_dir: "/opt/docker"
docker_compose_workdir: "{{ docker_compose_dir }}/{{ docker_compose_project_name }}"
docker_ansible_user: 'root'
docker_container_pwds: "1234"